### ISSUE TITLE
open source this

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/angular-eha.ebola-exposures#1]
Please confirm that this repo does not contain sensitive info

**Comment by danse** [comment]
pulling in @tthew because he can probably skim through the files very quickly, and @rmehner so he can also review the logic

**Comment by tthew** [comment]
Can't see any sensitive information, but the README needs some work. Could use some pruning.

**Comment by danse** [comment]
@tthew this is what the generator spits out, it might be an issue to create on the generator repo, not here

**Comment by rmehner** [comment]
:+1:

**Comment by danse** [comment]
:tada:
